### ISSUE TITLE
You can provide an example that can be used？

### ISSUE THREAD

**Issue by SoftwareKing** [enadim/spring-cloud-ribbon-extensions#2]
You can provide an example that can be used？

**Comment by SoftwareKing** [comment]
@enadim @ouaibsky

**Comment by enadim** [comment]
@see the examples and it sources

**Comment by zhaijp** [comment]
I use this but cannot start up and prompt ： Parameter 0 of method strictMetadataMatcher in com.github.enadim.spring.cloud.ribbon.support.StrictMetadataMatcherConfig required a bean of type 'com.netflix.client.config.IClientConfig' that could not be found.

**Comment by zhaijp** [comment]
@enadim @ouaibsky  Can you help me
